language: java
jdk:
  - openjdk8

branches:
  only:
    - main
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
 - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r spring-nginx-CD *
  - mkdir -p deploy
  - mv spring-nginx-CD.zip deploy/spring-nginx-CD.zip
  
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY 
    secret_access_key: $AWS_SECRET_KEY
  
    bucket: springboot-build-helloworld
    region: ap-northeast-2
    skip_cleanup: true
    acl:private
    local_dir: deploy
    wait-until-deployed: true

notifications:
  email:
    recipients:
